name: "Gitleaks Scan"
on:
  push:
    branches:
      - main
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install Snyk CLI
      run: npm install -g snyk
    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_API_TOKEN }}
    - name: Scan for secrets
      run: |
      snyk test --file=secrets.txt
      snyc test --file=DB-PASSWD.txt
