name: "Gitleaks Scan"
on:
  push:
    branches:
      - main
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install gitleaks
      run: |
        wget https://github.com/zricethezav/gitleaks/releases/download/v7.2.0/gitleaks-linux-amd64
        chmod +x gitleaks-linux-amd64
        sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks
    - name: Scan for secrets
      run: |
        gitleaks --verbose --redact --config=gitleaks.toml
